package exceptionDemo;

public class Example3 {
	
	void m1() {
		try {
			
		}catch(ArithmeticException ae) {
			
		}finally {
			
		}
		
	}

}
